name: Run Python script to generate portfolio

on:
  push:
    branches:
      - master

jobs:
  run_script_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run portfolio generation script
        run: |
          python generate_portfolio.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || (git commit -m "Auto-Update portfolio [skip ci]" && git push)
